-- Migration: add new columns to the supplier table
-- Run once against the live DB before restarting the server.
-- MySQL 8.0+ supports IF NOT EXISTS for ADD COLUMN.

ALTER TABLE supplier ADD COLUMN IF NOT EXISTS REGISTRATION_NO      VARCHAR(50)    NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS COMPANY_TYPE         VARCHAR(50)    NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS WEBSITE              VARCHAR(200)   NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS ALTERNATE_EMAIL      VARCHAR(120)   NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS ALTERNATE_PHONE      VARCHAR(30)    NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS YEARS_IN_BUSINESS    INT            NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS ANNUAL_TURNOVER      DECIMAL(18,2)  NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS EMPLOYEE_COUNT       INT            NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS CERTIFICATIONS       JSON           NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS ADVANCE_PERCENT      DECIMAL(5,2)   NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS CREDIT_DAYS          INT            NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS MINIMUM_ORDER_VALUE  DECIMAL(14,2)  NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS LEAD_TIME_DAYS       INT            NULL;
ALTER TABLE supplier ADD COLUMN IF NOT EXISTS DELIVERY_MODES       JSON           NULL;
